(() => {
'use strict';
const ASSET_DB='kejian-assets-v1', ASSET_STORE='assets';
let bgObjectUrl=null;
function openAssetDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(ASSET_DB,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(ASSET_STORE))db.createObjectStore(ASSET_STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function assetGet(key){const db=await openAssetDb();return new Promise((resolve,reject)=>{const tx=db.transaction(ASSET_STORE,'readonly');const r=tx.objectStore(ASSET_STORE).get(key);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}
async function assetPut(key,value){const db=await openAssetDb();return new Promise((resolve,reject)=>{const tx=db.transaction(ASSET_STORE,'readwrite');tx.objectStore(ASSET_STORE).put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function assetDelete(key){const db=await openAssetDb();return new Promise((resolve,reject)=>{const tx=db.transaction(ASSET_STORE,'readwrite');tx.objectStore(ASSET_STORE).delete(key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function applyAppearance(){try{const bg=await assetGet('background');if(bg){if(bgObjectUrl)URL.revokeObjectURL(bgObjectUrl);bgObjectUrl=URL.createObjectURL(bg);document.body.style.backgroundImage=`url(${JSON.stringify(bgObjectUrl)})`;document.body.classList.add('custom-background')}else{document.body.style.backgroundImage='';document.body.classList.remove('custom-background')}const icon=await assetGet('icon180');if(icon){if('serviceWorker'in navigator)await navigator.serviceWorker.ready.catch(()=>null);const stamp=Date.now();document.querySelector('link[rel="apple-touch-icon"]')?.setAttribute('href',`./custom-apple-touch-icon.png?v=${stamp}`);document.querySelector('link[rel="icon"]')?.setAttribute('href',`./custom-icon-192.png?v=${stamp}`)}else{document.querySelector('link[rel="apple-touch-icon"]')?.setAttribute('href','icons/apple-touch-icon.png');document.querySelector('link[rel="icon"]')?.setAttribute('href','icons/icon-192.png')}}catch(e){console.warn('应用个性化图片失败',e)}}
async function loadImage(file){const url=URL.createObjectURL(file);try{return await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=url})}finally{setTimeout(()=>URL.revokeObjectURL(url),0)}}
async function resizeImage(file,{max=1920,size=null,type='image/jpeg',quality=.9}={}){const img=await loadImage(file);let sx=0,sy=0,sw=img.naturalWidth,sh=img.naturalHeight,w,h;if(size){const side=Math.min(sw,sh);sx=(sw-side)/2;sy=(sh-side)/2;sw=sh=side;w=h=size}else{const scale=Math.min(1,max/Math.max(sw,sh));w=Math.max(1,Math.round(sw*scale));h=Math.max(1,Math.round(sh*scale))}const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,sx,sy,sw,sh,0,0,w,h);return await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('图片处理失败')),type,quality))}
async function setBackgroundFromFile(file){const blob=await resizeImage(file,{max:1920,type:'image/jpeg',quality:.88});await assetPut('background',blob);await applyAppearance()}
async function setHomeIconFromFile(file){const [i180,i192,i512]=await Promise.all([resizeImage(file,{size:180,type:'image/png'}),resizeImage(file,{size:192,type:'image/png'}),resizeImage(file,{size:512,type:'image/png'})]);await Promise.all([assetPut('icon180',i180),assetPut('icon192',i192),assetPut('icon512',i512)]);await applyAppearance()}
function bind({toast,closePanel}){const bg=document.querySelector('#backgroundFileInput'),icon=document.querySelector('#homeIconFileInput');document.querySelector('#backgroundImageButton').onclick=()=>bg.click();bg.onchange=async()=>{const f=bg.files?.[0];if(!f)return;try{await setBackgroundFromFile(f);closePanel();toast('课表背景已更新')}catch(e){alert('背景设置失败：'+e.message)}finally{bg.value=''}};document.querySelector('#clearBackgroundButton').onclick=async()=>{await assetDelete('background');await applyAppearance();closePanel();toast('已恢复默认背景')};document.querySelector('#homeIconButton').onclick=()=>icon.click();icon.onchange=async()=>{const f=icon.files?.[0];if(!f)return;try{await setHomeIconFromFile(f);closePanel();toast('桌面图标已更新；iPhone 请删除旧图标后重新添加到主屏幕')}catch(e){alert('图标设置失败：'+e.message)}finally{icon.value=''}};document.querySelector('#resetHomeIconButton').onclick=async()=>{await Promise.all(['icon180','icon192','icon512'].map(assetDelete));await applyAppearance();closePanel();toast('已恢复默认桌面图标；重新添加到主屏幕后生效')}}
window.KejianAppearance={init:applyAppearance,bind};
})();
