(() => {
'use strict';
const COLORS=['#6b8fbd','#7b78b8','#639a8a','#b8817a','#758ea8','#8b7cab','#6f9678','#a08362','#7189a8','#8b819e'];
const DEFAULT_TIMES=[['08:00','08:45'],['08:55','09:40'],['10:00','10:45'],['10:55','11:40'],['14:00','14:45'],['14:55','15:40'],['16:00','16:45'],['16:55','17:40'],['19:00','19:45'],['19:55','20:40'],['21:00','21:45'],['21:55','22:40']];
function uid(){return Math.random().toString(36).slice(2,10)+Date.now().toString(36)}
function weeksToSet(expr,term=60){const out=new Set();if(!expr)return out;let raw=String(expr).replace(/[，、；;]/g,',').replace(/[—–~～至]/g,'-').replace(/\s+/g,'');for(let part of raw.split(',').filter(Boolean)){const odd=/单/.test(part),even=/双/.test(part);part=part.replace(/第/g,'').replace(/周/g,'').replace(/[()（）\[\]【】单双全]/g,'');if(!part){for(let i=1;i<=term;i++){if(odd&&i%2===0)continue;if(even&&i%2===1)continue;out.add(i)}continue}const m=part.match(/(\d+)(?:-(\d+))?/);if(!m)continue;let a=+m[1],b=m[2]?+m[2]:a;if(a>b)[a,b]=[b,a];for(let i=a;i<=b&&i<=term;i++){if(odd&&i%2===0)continue;if(even&&i%2===1)continue;out.add(i)}}return out}
function normalizeWeeks(expr){const nums=[...weeksToSet(expr,60)].sort((a,b)=>a-b);if(!nums.length)return String(expr||'').replace(/第|周/g,'').trim();const out=[];let a=nums[0],p=nums[0];for(let i=1;i<=nums.length;i++){const n=nums[i];if(n===p+1){p=n;continue}out.push(a===p?String(a):`${a}-${p}`);a=p=n}return out.join(',')}
function maxWeek(expr){const a=[...weeksToSet(expr,60)];return a.length?Math.max(...a):0}
function parseSections(txt,fallbackStart=1,classNum=1){const m=String(txt||'').match(/(\d+)\s*[-—–~～至]\s*(\d+)\s*节/);if(m)return[+m[1],+m[2]];const n=String(txt||'').match(/(\d+)\s*节/);if(n)return[+n[1],+n[1]];return[fallbackStart,fallbackStart+Math.max(1,+classNum||1)-1]}
function finishCourses(map){const courses=[...map.values()];for(const c of courses){const teachers=[...new Set(c.slots.map(s=>s.teacher).filter(Boolean))];if(!c.teacher&&teachers.length)c.teacher=teachers[0];const locs=[...new Set(c.slots.map(s=>s.location).filter(Boolean))];if(locs.length===1)c.location=locs[0];c.slots=c.slots.filter((s,i,a)=>a.findIndex(x=>x.day===s.day&&x.start===s.start&&x.end===s.end&&x.weeks===s.weeks&&x.location===s.location&&x.teacher===s.teacher)===i)}return courses}
function parseUrpDocument(doc){const blocks=[...doc.querySelectorAll('#courseTable .class_div')];if(!blocks.length)return null;const map=new Map();blocks.forEach(block=>{const td=block.closest('td[id]');const idm=td?.id?.match(/^(\d+)_(\d+)$/);if(!idm)return;const day=+idm[1],fallbackStart=+idm[2];if(day<1||day>7)return;const ps=[...block.children].filter(n=>n.tagName==='P');const gray=ps.filter(p=>p.classList.contains('kcb_p_gray'));const name=(ps.find(p=>[...p.classList].some(c=>c.startsWith('p-kcm-')))||ps[0])?.textContent.trim();if(!name)return;const teacher=(gray[0]?.textContent||'').trim().replace(/\*+$/,'').trim();const weeks=normalizeWeeks(gray[1]?.textContent||'');const sec=gray[2]?.textContent||'';const loc=(ps.find(p=>[...p.classList].some(c=>c.startsWith('p-jxl-')))||ps[4])?.textContent.trim()||'';const [start,end]=parseSections(sec,fallbackStart,block.getAttribute('classnum'));const key=name;let c=map.get(key);if(!c){c={id:uid(),name,teacher,location:'',color:COLORS[map.size%COLORS.length],note:'',slots:[]};map.set(key,c)}c.slots.push({id:uid(),day,start,end,weeks:weeks||'1-20',location:loc,teacher})});const times=DEFAULT_TIMES.map(x=>[...x]);for(let i=1;i<=12;i++){const th=doc.getElementById(`0_${i}`);const m=th?.textContent.match(/(\d{2}:\d{2})\s*[-—–~～至]\s*(\d{2}:\d{2})/);if(m)times[i-1]=[m[1],m[2]]}let currentWeekHint=null;for(const node of doc.querySelectorAll('.span_bbzx')){const m=node.textContent.match(/第\s*(\d+)\s*周/);if(m){currentWeekHint=+m[1];break}}return{source:'烟台大学 URP',courses:finishCourses(map),times,currentWeekHint,rawCount:blocks.length,maxSections:12}}
function detailText(block,titlePart){const marker=[...block.querySelectorAll('[title]')].find(n=>(n.getAttribute('title')||'').includes(titlePart));return marker?.closest('p')?.textContent?.replace(/\s+/g,' ').trim()||''}
function cleanHmcName(name){return String(name||'').trim().replace(/[◆◇]+$/,'').trim()}
function parseHmcDocument(doc){const table=doc.querySelector('#kbgrid_table_0');if(!table)return null;const blocks=[...table.querySelectorAll('td[id].td_wrap .timetable_con')];if(!blocks.length)return null;const map=new Map();let rawCount=0,maxSections=12;for(const block of blocks){const titleFont=block.querySelector('.title font');if((titleFont?.getAttribute('color')||'').toLowerCase()==='red')continue;const td=block.closest('td[id]');const idm=td?.id?.match(/^(\d+)-(\d+)$/);if(!idm)continue;const day=+idm[1],fallbackStart=+idm[2];if(day<1||day>7)continue;const name=cleanHmcName(block.querySelector('.title')?.textContent);if(!name)continue;const timeText=detailText(block,'节/周');const [start,end]=parseSections(timeText,fallbackStart,1);maxSections=Math.max(maxSections,end);let weeksText=timeText.replace(/^.*?\)\s*/,'').trim();if(!weeksText){const m=block.textContent.match(/周数[:：]\s*([^\s]+)/);weeksText=m?.[1]||''}const weeks=normalizeWeeks(weeksText);const location=detailText(block,'上课地点').trim();const teacher=detailText(block,'教师').trim();const classText=detailText(block,'教学班名称').trim();const classCode=(classText.match(/\([^)]*\)-[^\s]+/)||[])[0]||classText;const key=name+'\u0000'+classCode;let c=map.get(key);if(!c){c={id:uid(),name,teacher,location:'',color:COLORS[map.size%COLORS.length],note:'',slots:[]};map.set(key,c)}c.slots.push({id:uid(),day,start,end,weeks:weeks||'1-20',location,teacher});rawCount++}return{source:'杭州医学院正方教务',courses:finishCourses(map),times:null,currentWeekHint:null,rawCount,maxSections}}
function parseCourseHtml(html){const doc=new DOMParser().parseFromString(html,'text/html');const parsed=parseUrpDocument(doc)||parseHmcDocument(doc);if(!parsed)throw new Error('未识别到支持的课表结构。目前支持烟台大学 URP“选课结果”和杭州医学院正方教务“个人课表查询”保存的完整 HTML。');return parsed}
window.KejianImporters={weeksToSet,normalizeWeeks,maxWeek,parseCourseHtml};
})();
